#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.0b1 on Fri Oct 25 10:46:29 2024
#

from ft8wx import MyApp
#from ft8dc import ft8dc

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
import os,sys
from socket import socket, AF_INET, SOCK_DGRAM, SOCK_STREAM
import select
import threading
import subprocess
import json
import struct
import juliandate as jd
import time
import configparser
import math
import re
from datetime import datetime, timedelta, timezone
from typing import Dict, List, Tuple
import requests
from requests.exceptions import Timeout
import xml.etree.ElementTree as ET
from slack_sdk import WebClient
from slack_sdk.errors import SlackApiError
# end wxGlade

# end of class MyApp

if __name__ == "__main__":
#    ft8dc = ft8dc(0)
#    ft8dc.readadif()
    app = MyApp(0)
    app.MainLoop()
